apiVersion: apps/v1
kind: Deployment
metadata:
    name: shinobi-war-fairy-auth-ui
    namespace: default
    labels:
        app: shinobi-war-fairy-auth-ui
spec:
    replicas: 1
    selector:
        matchLabels:
            app: shinobi-war-fairy-auth-ui
    template:
        metadata:
            labels:
                app: shinobi-war-fairy-auth-ui
            annotations:
                dapr.io/enabled: 'true'
                dapr.io/app-id: 'auth-ui'
                dapr.io/app-port: '3001'
        spec:
            containers:
                - name: shinobi-war-fairy-auth-ui
                  image: registry.digitalocean.com/sw-fairy-k8s/sw-fairy-k8s-auth-ui:{{commitId}}
                  ports:
                      - containerPort: 3001
                        name: http
