apiVersion: v1
kind: Service
metadata:
  name: shinobi-war-fairy-login-ui
  namespace: default
  labels:
    app: shinobi-war-fairy-login-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: shinobi-war-fairy-login-ui
